- name: Install Brave
  become: true
  pacman:
    name: brave-browser
    state: latest
  tags:
    - brave
- name: Install 1Password
  become: true
  community.general.snap:
    name: 1password
  tags:
    - 1password
- name: Install Spotify
  become: true
  community.general.snap:
    name: spotify
  tags:
    - spotify
