- name: Install Fish
  become: true
  pacman:
    name: fish
    state: latest
  tags:
    - fish
# TODO: This won't set Fish as a default shell
# It's require user password for some reason
- name: Set Fish as default shell
  become: true
  shell: chsh -s `which fish`
  tags:
    - fish
# TODO: For some reason it hangs on below task
# Check that url or command modules can solve that.
- name: Install oh-my-fish
  shell: curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
  tags:
    - fish
- name: Get Fish dotfiles
  become: false
  ansible.builtin.git:
    repo: git@github.com:kamikazestar/fish.git
    dest: /home/kamikazestar/.config/fish
    single_branch: yes
    version: master
    update: no
  tags:
    - fish
- name: Install Peco
  become: true
  pacman:
    name: peco
    state: latest
  tags:
    - fish
- name: Install Z
  become: true
  pacman:
    name: z
    state: latest
  tags:
    - fish
