- name: Make sure we have a 'wheel' group
  become: true
  group:
    name: wheel
    state: present
  tags:
  - sudoers
- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
  - sudoers
