- name: Install Bottom
  become: true
  pacman:
    name: bottom
    state: latest
  tags:
    - bottom
- name: Install Ripgrep
  become: true
  pacman:
    name: ripgrep
    state: latest
  tags:
    - ripgrep
