---

- name: Install bat
  become: true
  ansible.builtin.package:
    name:
      - bat
    state: "{{ pkg_state }}"
  tags:
    - bat
    - extraSysUtils
    - system

- name: Create config directory for bat
  become: false
  ansible.builtin.file:
    path: "$(bat --config-dir)/themes"
    state: directory
    recurse: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  tags:
    - bat
    - extraSysUtils
    - system

- name: Get the Catppuccin theme for bat 
  become: false
  ansible.builtin.get_url:
    url: https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme
    dest: "$(bat --config-dir)/themes"
  tags:
    - bat
    - extraSysUtils
    - system

- name: Rebuild bat cache
  become: false
  ansible.builtin.command: bat cache --build
  tags:
    - bat
    - extraSysUtils
    - system

- name: Create bat config file
  become: false
  ansible.builtin.file:
    path: "{{ansible_user_dir}}/.config/bat/config"
    state: touch
  tags:
    - bat
    - extraSysUtils
    - system

- name: Set Catppuccin as default theme for bat
  become: false
  ansible.builtin.lineinfile:
    path: "{{ansible_user_dir}}/.config/bat/config"
    line: "--theme='Catppuccin Mocha'"
  tags:
    - bat
    - extraSysUtils
    - system
