---
- name: Install Fish
  become: true
  pacman:
    name: fish
    state: "{{ pkg_state }}"
  tags:
    - fish
    - system

- name: Set Fish as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    shell: /usr/bin/fish
  tags:
    - fish
    - system

- name: Get Fish dotfiles
  become: false
  ansible.builtin.git:
    repo: git@github.com:MikePapaSierra/fish.git
    dest: "{{ ansible_user_dir }}/.config/fish"
    accept_hostkey: true
    single_branch: yes
    version: master
    update: no
  tags:
    - fish
    - system

- name: Install Z
  become: true
  pacman:
    name: z
    state: "{{ pkg_state }}"
  tags:
    - z
    - fish
    - system

- name: Install Eza
  become: true
  pacman:
    name: eza
    state: "{{ pkg_state }}"
  tags:
    - eza
    - fish
    - system

- name: Install Figlet
  become: true
  pacman:
    name: figlet
    state: "{{ pkg_state }}"
  tags:
    - figlet
    - fish
    - system

- name: Install Lolcat
  become: true
  pacman:
    name: lolcat
    state: "{{ pkg_state }}"
  tags:
    - lolcat
    - fish
    - system

- name: Install figlet-fonts
  become: false
  ansible.builtin.git:
    repo: git@github.com:xero/figlet-fonts.git
    dest: "{{ ansible_user_dir }}/.local/share/fonts/figlet-fonts"
    single_branch: yes
    version: master
    update: no
  tags:
    - fonts
    - figlet
    - fish
    - system
