---
- name: Install Git
  become: true
  ansible.builtin.package:
    name: git
    state: "{{ pkg_state }}"
  tags:
    - git
    - system

- name: Get Git dotfiles
  become: false
  ansible.builtin.git:
    repo: git@github.com:MikePapaSierra/git.git
    dest: "{{ ansible_user_dir }}/.config/git"
    single_branch: yes
    version: main
    update: no
  tags:
    - git
    - system

- name: Create link for config file
  become: false
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/git/gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    state: link
  tags:
    - git
    - system

- name: Install Delta  as an pager for Git
  become: true
  ansible.builtin.package:
    name:
      - git-delta
    state: "{{ pkg_state }}"
  tags:
    - delta
    - git
    - system

- name: Install Lazygit
  become: true
  pacman:
    name: lazygit
    state: "{{ pkg_state }}"
  tags:
    - lazygit
    - git
    - system

- name: Get Lazygit config
  become: false
  ansible.builtin.git:
    repo: git@github.com:MikePapaSierra/lazygit.git
    dest: "{{ ansible_user_dir }}/.config/lazygit"
    single_branch: true
    version: main
    update: no
  tags:
    - lazygit
    - git
    - system

- name: Install Commitizen
  kewlfft.aur.aur:
    name: commitizen-go
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - commitizen
    - git
    - system
