---
- name: Install Kitty
  become: true
  pacman:
    name: [ kitty, kitty-shell-integration, kitty-terminfo ]
    state: "{{ pkg_state }}"
  tags:
    - kitty
    - terminal
    - gui
    - system

- name: Get Kitty dotfiles
  become: false
  ansible.builtin.git:
    repo: git@github.com:MikePapaSierra/kitty.git
    dest: /home/{{ username }}/.config/kitty
    single_branch: yes
    version: main
    update: no
  tags:
    - kitty
    - terminal
    - gui
    - system
