---
- name: Install Neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: "{{ pkg_state }}"
  tags:
    - neovim
    - editors
    - system

- name: Install Python3 provider
  become: true
  ansible.builtin.package:
    name: python-pynvim
    state: "{{ pkg_state }}"
  tags:
    - neovim
    - editors
    - system

- name: Get Neovim dotfiles
  become: false
  ansible.builtin.git:
    dest: /home/kamikazestar/.config/nvim
    repo: git@github.com:MikePapaSierra/nvim.git
    single_branch: yes
    version: master
    update: no
  tags:
    - neovim
    - editors
    - system

