---
- name: Install Snap
  become: true
  ansible.builtin.package:
    name: snapd
    state: "{{ pkg_state }}"
  tags:
    - snap
    - system

- name: Enable Snap communication socket
  become: true
  ansible.builtin.systemd:
    name: snapd.socket
    enabled: true
    state: started
  tags:
    - snap
    - system

- name: Enable Snap AppArmor
  become: true
  ansible.builtin.systemd:
    name: snapd.apparmor
    enabled: true
    state: started
  tags:
    - snap
    - system

- name: Enable classic snap support
  become: true
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  tags:
    - snap
    - system

- name: Create link for snapd applications
  become: false
  ansible.builtin.file:
    src: /var/lib/snapd/desktop/applications
    dest: /home/kamikazestar/.local/share/applications/snap
    state: link
  tags:
    - snap
    - system
