---
- name: Install Tmux
  become: true
  pacman:
    name: tmux
    state: "{{ pkg_state }}"
  tags:
    - tmux
    - system

- name: Get Tmux dotfiles
  become: false
  ansible.builtin.git:
    repo: git@github.com:kamikazestar/tmux.git
    dest: "{{ ansible_user_dir }}/.config/tmux"
    single_branch: yes
    version: master
    update: no
  tags:
    - tmux
    - system

- name: Create symlink to configuration file
  become: false
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link
  tags:
    - tmux
    - system
