---
- name: Check that users already exists
  become: true
  ansible.builtin.getent:
    database: passwd
    key: "{{ username }}"
  register: user_check

- name: Create a user account
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - docker
      - wheel
      - libvirt
      - power
      - network
      - storage
      - users
      - audio
      - input
      - lp
    append: yes
    state: present
    shell: /bin/fish
    system: false
    create_home: true
    home: /home/"{{ username }}"
  when: user_check is failed
  tags:
    - user-account
    - users

- name: Configure sudo
  ansible.builtin.import_tasks: sudo.yml
