---
- name: Create a user account
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    password:
    groups:
      - docker
      - wheel
      - libvirt
      - power
      - network
      - storage
      - users
      - audio
      - input
      - lp
    state: present
    shell: /bin/fish
    system: false
    create_home: true
    home: /home/"{{ username }}"
  tags:
    - user-account
    - users

- name: Configure sudo
  ansible.builtin.import_tasks: sudo.yml
