---
- name: Install FreeCAD
  become: true
  ansible.builtin.package:
    name: freecad
    state: "{{ pkg_state }}"
  tags:
    - freecad
    - diy
  when:
    - ansible_facts['form_factor'] == "Desktop"

- name: Install Cura
  kewlfft.aur.aur:
    name: cura-5-bin
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - cura
    - gui
    - diy
  when:
    - ansible_facts['form_factor'] == "Desktop"
