---
- name: Install AWS CLI v2
  kewlfft.aur.aur:
    name: aws-cli-v2
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - aws-cli
    - aws
    - cloud
    - development

- name: Install AWS CDK
  kewlfft.aur.aur:
    name: aws-cdk
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - aws-cdk
    - aws
    - cloud
    - development
