---
- name: Install Go
  become: true
  ansible.builtin.package:
    name: go
    state: "{{ pkg_state }}"
  tags:
    - go
    - development

- name: Install go-tools
  become: true
  ansible.builtin.package:
    name: go-tools
    state: "{{ pkg_state }}"
  tags:
    - go
    - development

- name: Check for GOPATH in Fish configuration
  become: false
  ansible.builtin.shell: grep -c "GOPATH" $HOME/.config/fish/config.fish
  register: fish_go_cfg
  tags:
    - go
    - development

- name: Set GOPATH
  become: false
  ansible.builtin.lineinfile:
    dest: "{{ ansible_user_dir }}/.config/fish/config.fish"
    line: "if [ -d $HOME/go ]; set GOPATH $HOME/go; set PATH $HOME/go/bin $PATH; end"
    notify: source $HOME/.config/fish/config.fish
  when: fish_go_cfg.stdout == "0"
  tags:
    - go
    - development
