---
- name: Install Terraform
  become: true
  ansible.builtin.package:
    name: terraform
    state: "{{ pkg_state }}"
  tags:
    - terraform
    - cloud
    - development

- name: Install TFLint
  become: true
  ansible.builtin.package:
    name: tflint
    state: "{{ pkg_state }}"
  tags:
    - tflint
    - terraform
    - cloud
    - development

- name: Install pre-commit
  become: true
  ansible.builtin.package:
    name: pre-commit
    state: "{{ pkg_state }}"
  tags:
    - pre-commit
    - terraform
    - cloud
    - development
