---
- name: Install Vagrant
  become: true
  ansible.builtin.package:
    name: vagrant
    state: "{{ pkg_state }}"
  tags:
    - vm
    - vagrant

- name: Install and configure Qemu
  ansible.builtin.import_tasks: qemu.yml

- name: Install and configure VirtualBox
  ansible.builtin.import_tasks: virtualbox.yml
