---
- name: Install Spotify
  kewlfft.aur.aur:
    name: spotify
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - spotify
    - gui
    - media

- name: Install Spotifyd
  become: true
  pacman:
    name: spotifyd
    state: "{{ pkg_state }}"
  tags:
    - spotifyd
    - spotify
    - media

- name: Install Spotify TUI
  kewlfft.aur.aur:
    name: spotify-tui
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - spotify
    - spotify-tui
    - media

# TODO: After installation only blank window is displayed
# This could be potential issue with Nvidia Opencl driver or jdk version.
- name: Install DaVinci Resolve
  kewlfft.aur.aur:
    name: davinci-resolve
    use: yay
    state: "{{ pkg_state }}"
  tags:
    - davinci-resolve
    - gui
    - media
